// TIME KEEPER
export const GET_TIME_INITIATED = 'GET_TIME_INITIATED';
export const GETTING_TIME = 'GETTING_TIME';
export const GET_TIME_ERROR = 'GET_TIME_ERROR';
export const GET_TIME_SUCCESS = 'GET_TIME_SUCCESS';
export const UPDATE_TIME_INITIATED = 'UPDATE_TIME_INITIATED';
export const UPDATING_TIME = 'UPDATING_TIME';
export const UPDATE_TIME_ERROR = 'UPDATE_TIME_ERROR';
export const UPDATE_TIME_SUCCESS = 'UPDATE_TIME_SUCCESS';
